#pragma once
#include <map>

namespace sfmlAdapter
{
enum class Entity
{ // any better idea?
  Deck,
  Pile,
  TwoSpades,
  ThreeSpades,
  FourSpades,
  FiveSpades,
  SixSpades,
  SevenSpades,
  EightSpades,
  NineSpades,
  TenSpades,
  JackSpades,
  QueenSpades,
  KingSpades,
  AceSpades,
  TwoClubs,
  ThreeClubs,
  FourClubs,
  FiveClubs,
  SixClubs,
  SevenClubs,
  EightClubs,
  NineClubs,
  TenClubs,
  JackClubs,
  QueenClubs,
  KingClubs,
  AceClubs,
  TwoHearts,
  ThreeHearts,
  FourHearts,
  FiveHearts,
  SixHearts,
  SevenHearts,
  EightHearts,
  NineHearts,
  TenHearts,
  JackHearts,
  QueenHearts,
  KingHearts,
  AceHearts,
  TwoDiamonds,
  ThreeDiamonds,
  FourDiamonds,
  FiveDiamonds,
  SixDiamonds,
  SevenDiamonds,
  EightDiamonds,
  NineDiamonds,
  TenDiamonds,
  JackDiamonds,
  QueenDiamonds,
  KingDiamonds,
  AceDiamonds
};

using Entities = std::vector<sfmlAdapter::Entity>;

constexpr std::initializer_list<Entity> entities_all = {
    Entity::Deck,          Entity::Pile,          Entity::TwoSpades,
    Entity::ThreeSpades,   Entity::FourSpades,    Entity::FiveSpades,
    Entity::SixSpades,     Entity::SevenSpades,   Entity::EightSpades,
    Entity::NineSpades,    Entity::TenSpades,     Entity::JackSpades,
    Entity::QueenSpades,   Entity::KingSpades,    Entity::AceSpades,
    Entity::TwoClubs,      Entity::ThreeClubs,    Entity::FourClubs,
    Entity::FiveClubs,     Entity::SixClubs,      Entity::SevenClubs,
    Entity::EightClubs,    Entity::NineClubs,     Entity::TenClubs,
    Entity::JackClubs,     Entity::QueenClubs,    Entity::KingClubs,
    Entity::AceClubs,      Entity::TwoHearts,     Entity::ThreeHearts,
    Entity::FourHearts,    Entity::FiveHearts,    Entity::SixHearts,
    Entity::SevenHearts,   Entity::EightHearts,   Entity::NineHearts,
    Entity::TenHearts,     Entity::JackHearts,    Entity::QueenHearts,
    Entity::KingHearts,    Entity::AceHearts,     Entity::TwoDiamonds,
    Entity::ThreeDiamonds, Entity::FourDiamonds,  Entity::FiveDiamonds,
    Entity::SixDiamonds,   Entity::SevenDiamonds, Entity::EightDiamonds,
    Entity::NineDiamonds,  Entity::TenDiamonds,   Entity::JackDiamonds,
    Entity::QueenDiamonds, Entity::KingDiamonds,  Entity::AceDiamonds};

const std::map<Entity, std::string> hashedTextureNames{
    {Entity::Deck, "cardBack"},           {Entity::Pile, "cardBack"},
    {Entity::TwoSpades, "spades2"},       {Entity::ThreeSpades, "spades3"},
    {Entity::FourSpades, "spades4"},      {Entity::FiveSpades, "spades5"},
    {Entity::SixSpades, "spades6"},       {Entity::SevenSpades, "spades7"},
    {Entity::EightSpades, "spades8"},     {Entity::NineSpades, "spades9"},
    {Entity::TenSpades, "spades10"},      {Entity::JackSpades, "spades11"},
    {Entity::QueenSpades, "spades12"},    {Entity::KingSpades, "spades13"},
    {Entity::AceSpades, "spades1"},       {Entity::TwoClubs, "clubs2"},
    {Entity::ThreeClubs, "clubs3"},       {Entity::FourClubs, "clubs4"},
    {Entity::FiveClubs, "clubs5"},        {Entity::SixClubs, "clubs6"},
    {Entity::SevenClubs, "clubs7"},       {Entity::EightClubs, "clubs8"},
    {Entity::NineClubs, "clubs9"},        {Entity::TenClubs, "clubs10"},
    {Entity::JackClubs, "clubs11"},       {Entity::QueenClubs, "clubs12"},
    {Entity::KingClubs, "clubs13"},       {Entity::AceClubs, "clubs1"},
    {Entity::TwoHearts, "hearts2"},       {Entity::ThreeHearts, "hearts3"},
    {Entity::FourHearts, "hearts4"},      {Entity::FiveHearts, "hearts5"},
    {Entity::SixHearts, "hearts6"},       {Entity::SevenHearts, "hearts7"},
    {Entity::EightHearts, "hearts8"},     {Entity::NineHearts, "hearts9"},
    {Entity::TenHearts, "hearts10"},      {Entity::JackHearts, "hearts11"},
    {Entity::QueenHearts, "hearts12"},    {Entity::KingHearts, "hearts13"},
    {Entity::AceHearts, "hearts1"},       {Entity::TwoDiamonds, "diamonds2"},
    {Entity::ThreeDiamonds, "diamonds3"}, {Entity::FourDiamonds, "diamonds4"},
    {Entity::FiveDiamonds, "diamonds5"},  {Entity::SixDiamonds, "diamonds6"},
    {Entity::SevenDiamonds, "diamonds7"}, {Entity::EightDiamonds, "diamonds8"},
    {Entity::NineDiamonds, "diamonds9"},  {Entity::TenDiamonds, "diamonds10"},
    {Entity::JackDiamonds, "diamonds11"}, {Entity::QueenDiamonds, "diamonds12"},
    {Entity::KingDiamonds, "diamonds13"}, {Entity::AceDiamonds, "diamonds1"}};
} // namespace sfmlAdapter